spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
